# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  pool:
    name: Default
    demands:
    - Agent.Name -equals 'jf-aswf-gpu'
    - Agent.Version -equals 2.153.2

  steps:
  - script: nvidia-smi
    displayName: 'Run a one-line script'

