# Demonstrate that OpenGL is available when building inside a container

trigger:
- master

jobs:
- job: Linux
  pool:
    name: 'GPU Ubuntu 18.04'
  container:
    image: aswftesting/ci-ocio:2019.1
    options: --gpus all

  steps:
  - script: DISPLAY=:0.0 glxinfo
    displayName: 'Run a one-line script'

